_apt_key:
  - url: https://downloadcontent.opensuse.org/repositories/home:/alvistack/Debian_Testing/Release.key
    dest: /etc/apt/keyrings/home-alvistack.asc
    checksum: "sha256:2959bf5709615cba0109715e4c2001066a4536398fa54f0f602abc208f04017e"
