---
galaxy_info:
  author: Richard Slater
  description: "Ansible role to install SpecKit using the uv package manager."
  license: "MIT"
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
dependencies:
  - uv
