---
oh_my_posh_bin_path: "/usr/local/bin/oh-my-posh"

# Architecture mapping for Oh My Posh downloads
oh_my_posh_arch_map:
  x86_64: "amd64"
  aarch64: "arm64"
  riscv64: "riscv64"

oh_my_posh_arch: "{{ oh_my_posh_arch_map[ansible_architecture] | default('amd64') }}"
oh_my_posh_supported_architectures:
  - x86_64
  - aarch64
  - riscv64
